### ISSUE TITLE
[1.0.0] Cluster spacing option changes size of chunk clusters.

### ISSUE THREAD

**Issue by Tokeli** [jglrxavpok/Chunk-Survival#1]
I've tried to increase the size between clusters, but it also increases the size OF the clusters themselves!

**Comment by jglrxavpok** [comment]
I've probably messed my math up... I'll fix this as soon as possible!

**Comment by jglrxavpok** [comment]
My math was actually correct, I simply copy-pasted the code to retrieve the value from the sliders too fast and forgot to change the slider used for the size...

Fixed in commit bbea84b6fe1feaa1b457fdf081391a9a1ad1c0f2

This issue will be fixed in version 1.0.1 which will be out soon(tm)
